/// SHA256 hashes for pre-built native library binaries.
///
/// Generated by the release CI workflow. Do not edit manually.
/// Keys follow the pattern: `{commit_short}-{os}-{arch}`
const assetHashes = <String, String>{};
