// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libghostty binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the tarballs.
// For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'libghostty-v0.0.1-dev.3';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames.
const assetHashes = <String, String>{
  'libghostty-aarch64-ios.dylib': 'c282882c97e92d0c25b6557f6d54eec59f82cb4ec6017e22fb16696c65008db5',
  'libghostty-aarch64-linux-android.so': '861c9180f228c100f9bf1d737e15434c202026e7e4b800f535fd843da017ca78',
  'libghostty-aarch64-linux.so': '4b4cb765fee785e50687de6e0a7b6b26961fe53c02f5adc77ced3c61a9f96e38',
  'libghostty-aarch64-macos.dylib': '60f7f4448bbed951cceb37cd5d9bb865aa065d5c5f89b109d3b35add1e2ada7e',
  'libghostty-arm-linux-androideabi.so': '86e5e5768c5a0e1599b0b684635a51113605a8306022106550d2a8be4eedc3ba',
  'libghostty-wasm32-freestanding.wasm': '2dc7451d8f6ac3cc999f749461279fbfe69b67dbcb530fdfa98c2715eb5f97eb',
  'libghostty-x86_64-linux-android.so': '7b1ea15de6635a86b1b8e2f8af0450993dfd71bce7c43e4407281a300e8b69aa',
  'libghostty-x86_64-linux-musl.so': '0a7cc649f400360ccd42a3ba701a6cfdae04b6c385b4037eec088bed4c4e5984',
  'libghostty-x86_64-linux.so': '79abdcd3c5737e94d773c503c8342c68ada73dba770047dbe562258c7436a6d9',
  'libghostty-x86_64-macos.dylib': '4f09fc502c5b378a33ed695bafef3527dabf2bff3c80d178cd9f5bd726d8af90',
  'libghostty-x86_64-windows.dll': 'ebb6ca7c2355b5345fe2cba159b0eb7d917dcf7145eb4b3cd4b2b4c1ab21f223',
};
