// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libghostty binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the tarballs.
// For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/write_asset_hashes.dart
// Release: v0.0.1-dev.1

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag these hashes were generated from, or null if not generated 
/// from a release.
const releaseTag = 'v0.0.1-dev.1';

/// SHA256 hashes for pre-built native binaries.
const assetHashes = <String, String>{};
