import 'package:meta/meta.dart';

import 'bindings/bindings.dart';
import 'enums/key.dart';
import 'enums/key_action.dart';
import 'enums/mods.dart';
import 'exceptions.dart';

/// A keyboard input event for terminal key encoding.
///
/// ```dart
/// final event = KeyEvent()
///   ..action = KeyAction.press
///   ..key = Key.keyC
///   ..mods = Mods.ctrl;
///
/// // Use with KeyEncoder...
///
/// event.dispose();
/// ```
class KeyEvent {
  static final _finalizer = Finalizer<int>(
    (handle) => bindings.keyEventFree(handle),
  );

  final int _handle;
  var _disposed = false;

  KeyEvent() : _handle = bindings.keyEventNew() {
    _finalizer.attach(this, _handle, detach: this);
  }

  /// The key action for this event.
  KeyAction get action {
    _ensureNotDisposed();
    return KeyAction.fromNative(bindings.keyEventGetAction(_handle));
  }

  set action(KeyAction value) {
    _ensureNotDisposed();
    bindings.keyEventSetAction(_handle, value.nativeValue);
  }

  /// Whether the key is part of a composition sequence.
  bool get composing {
    _ensureNotDisposed();
    return bindings.keyEventGetComposing(_handle);
  }

  set composing(bool value) {
    _ensureNotDisposed();
    bindings.keyEventSetComposing(_handle, value);
  }

  /// Modifier flags already consumed by the input method.
  Mods get consumedMods {
    _ensureNotDisposed();
    return Mods(bindings.keyEventGetConsumedMods(_handle));
  }

  set consumedMods(Mods value) {
    _ensureNotDisposed();
    bindings.keyEventSetConsumedMods(_handle, value.value);
  }

  /// The physical key code.
  Key get key {
    _ensureNotDisposed();
    return Key.fromNative(bindings.keyEventGetKey(_handle));
  }

  set key(Key value) {
    _ensureNotDisposed();
    bindings.keyEventSetKey(_handle, value.nativeValue);
  }

  /// Active keyboard modifier flags.
  Mods get mods {
    _ensureNotDisposed();
    return Mods(bindings.keyEventGetMods(_handle));
  }

  set mods(Mods value) {
    _ensureNotDisposed();
    bindings.keyEventSetMods(_handle, value.value);
  }

  @internal
  int get nativeHandle {
    _ensureNotDisposed();
    return _handle;
  }

  /// The Unicode codepoint without Shift applied.
  int get unshiftedCodepoint {
    _ensureNotDisposed();
    return bindings.keyEventGetUnshiftedCodepoint(_handle);
  }

  set unshiftedCodepoint(int value) {
    _ensureNotDisposed();
    bindings.keyEventSetUnshiftedCodepoint(_handle, value);
  }

  /// The UTF-8 text generated by this key event, or null if none.
  String? get utf8 {
    _ensureNotDisposed();
    return bindings.keyEventGetUtf8(_handle);
  }

  set utf8(String? value) {
    _ensureNotDisposed();
    bindings.keyEventSetUtf8(_handle, value);
  }

  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _finalizer.detach(this);
    bindings.keyEventFree(_handle);
  }

  void _ensureNotDisposed() {
    if (_disposed) throw const DisposedException('KeyEvent');
  }
}
